### ISSUE TITLE
Issue with FHIR.Local RequestHandler operation

### ISSUE THREAD

**Issue by jonastle** [intersystems/Samples-FHIRStarter#5]
I have downloaded the project and imported it into my local copy of IRIS.  I am trying to test the legacy HL7 to FHIR components.
I have dropped the test HL7 message into the import folder however I am receiving an error on the FHIR.Local
RequestHandler operation.

ERROR <Ens>ErrBPTerminated: Terminating BP Data.Process.SDAtoFHIR # due to error: ERROR #5770: Object open failed because 'ServiceIdIdx' key value of '' was not found
> ERROR #5770: Object open failed because 'ServiceIdIdx' key value of '' was not found

**Comment by jmorg85-isc** [comment]
Please confirm two key parts of this investigation.

1. What is the product and version of InterSystems software that your local copy is running?  IRIS or IRIS for Health and 202x.x?
2. What is the name of the file that is being dropped into the input folder? "HL7toFHIR.hl7" or "HL7v2_ORU_R01.hl7"?

**Comment by jonastle** [comment]
This is Healthshare Healthconnect 2021.1 with IRIS as the backend core database.
I have tried dropping in the HL7toFHIR.hl7 file and also ISCPATIENTtoFHIR.xml and I get the same error for both files.

Type: | Error
Text: | ERROR #5770: Object open failed because 'ServiceIdIdx' key value of '' was not found
Logged: | 2021-09-27 10:23:12.304
Source: | FHIR.Local.RequestHandler
Session: | 49
Job: | 17848
Class: | HS.FHIRServer.Interop.Operation
Method: | MessageHeaderHandler
Trace: | (none)
Stack: | $^zMessageHeaderHandler+216^HS.FHIRServer.Interop.Operation.1 +2$^zOnTask+42^Ens.Host.1 +1DO^zStart+62^Ens.Job.1 +2

**Comment by jmorg85-isc** [comment]
Thank you for confirming.

According to our Documentation, HealthShare Health Connect requires a special license to work with the FHIR Resource Repository.

[FHIR Components in Health Connect](https://docs.intersystems.com/healthconnectlatest/csp/docbook/DocBook.UI.Page.cls?KEY=HXFHIR_fhir#HXFHIR_fhir_components)

> "Depending on your product’s license, you might not be able to install a FHIR server with the Resource Repository."

This container and demonstration was only tested on IRIS for Health due to the potential of Health Connect instances requiring special consideration to leverage the FHIR Resource Repository.  The free, IRIS for Health Community edition is available for download with a license built in.  Are you able to use IRIS for Health?  If not, can you confirm if your Health Connect license is FHIR enabled?
